CREATE TABLE IF NOT EXISTS "nba_rankings_2014_2020" (
    "RowIndex" INT,
    "PLAYER" TEXT,
    "TEAM" TEXT,
    "AGE" INT,
    "SEASON" TEXT,
    "GP" INT,
    "W" INT,
    "L" INT,
    "MIN" NUMERIC(3, 1),
    "PTS" NUMERIC(3, 1),
    "FGM" NUMERIC(3, 1),
    "FGA" NUMERIC(3, 1),
    "FG" NUMERIC(4, 1),
    "ThreePM" NUMERIC(2, 1),
    "ThreePA" NUMERIC(3, 1),
    "ThreeP" NUMERIC(4, 1),
    "FTM" NUMERIC(3, 1),
    "FTA" NUMERIC(3, 1),
    "FT" NUMERIC(4, 1),
    "OREB" NUMERIC(2, 1),
    "DREB" NUMERIC(3, 1),
    "REB" NUMERIC(3, 1),
    "AST" NUMERIC(3, 1),
    "TOV" NUMERIC(2, 1),
    "STL" NUMERIC(2, 1),
    "BLK" NUMERIC(2, 1),
    "PF" NUMERIC(2, 1),
    "FP" NUMERIC(3, 1),
    "DD2" NUMERIC(3, 1),
    "TD3" NUMERIC(3, 1),
    "plusminus" NUMERIC(3, 1),
    "rankings" NUMERIC(3, 1)
);